name: Build and Deploy Flask App

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger the workflow for pull requests to 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t flask-app .

    # Step 3: Deploy the app
    - name: Deploy Flask App
      run: |
        docker run -d -p 5000:5000 flask-app
